#!/bin/bash
bspc config border_width            1
bspc config window_gap              15

bspc config split_ratio             0.70
bspc config bottom_padding          0
bspc config auto_cancel             true
bspc config focus_follows_pointer   false
bspc config pointer_follows_monitor true
bspc config auto_alternate          true

# see https://github.com/baskerville/bspwm/issues/143#issuecomment-42646522
# bspc monitor -d • • • • • • • • • •
if [[ $(hostname) == 'Nortonspeal04' ]]; then
    bspc monitor VGA-1 -d I II III IV V VI VII VIII IX X R
    xrandr --output LVDS1 --off
    # bspc monitor HDMI1 -d I II III IV V VI VII VIII IX X
    # bspc monitor eDP1 -d I II III IV V VI VII VIII IX X
elif [[ $(hostname) == 'otherhost' ]]; then
    bspc monitor VGA-1 -d I II III IV V VI VII VIII IX X
    bspc monitor HDMI1 -d I II III IV V VI VII VIII IX X
    # bspc monitor VGA-0 -d I II III IV V
    # bspc monitor VGA-1 -d VI VII VIII IX X
elif [[ $(hostname) == 'yetanotherhost' ]]; then
    bspc monitor DVI-I-3 -d VI VII VIII IX X
    bspc monitor DVI-I-2 -d I II III IV V
fi
# bspc monitor LVDS1 -d I II III IV V VI VII VIII IX X
# bspc monitor LVDS1 -d IX X
# bspc monitor HDMI1 -d I II III IV V VI VII VIII IX X
# trap 'jobs -p | xargs kill' EXIT

# ~/.config/bspwm/init &

# wait

# xrandr --output LVDS1 --off
# compton=~/.config/compton.conf
# compton=/usr/bin/compton
# dunst=/usr/local/bin/
# dunst=/usr/bin/dunst

# bspdir=$(dirname $(readlink -f $0))
# cd $bspdir

# TODO Troubleshoot utility
xmodmap -e 'clear Lock' -e 'keycode 0x42 = Escape'

# hide mouse on writting
if $(hash unclutter); then
    unclutter -idle 1 &
fi

# music daemon
if $(hash mpd); then
    mpd &
fi

# gnome settings daemon (for fonts and gtk styling)
# gnome-settings-daemon &

# set background
# gsettings set org.gnome.desktop.background picture-uri file:///home/user/Pictures/wallpaper.png
# ~/.config/bspwm/iq_utilities/terminal_transparency 8 &

# feh --bg-tile ~/.config/bspwm/wallpaper.jpg &
feh --bg-tile ~/.config/tq_wallpaper &

# launch oq_dunst
# [[ -e $dunst ]] \
#     && $dunst -config $bspdir/vq_panels/dunstrc &
# dunst -config ~/.config/dunst/dunstrc
dunst &

# launch compton compositor
# [[ -e $compton]] \
    # && $compton --config ~/config/compton.conf &
# compton --config ~/config/compton.conf &
compton &

# launch dzen2 panels
~/.config/bspwm/vq_panels/topbar &
~/.config/bspwm/vq_panels/status &

# launch battery checker
# $bspdir/iq_utilities/battery_alert &

# sleep 5 && $bspdir/iq_utilities/hide dzen2-bottom-status-bar

wait
# xrandr --output LVDS-1 --off

