#!/bin/bash
trap 'jobs -p | xargs kill' EXIT

compton=~/.config/bspwm/compton.conf
dunst=/usr/local/bin/

bspdir=$(dirname $(readlink -f $0))
cd $bspdir

xmodmap -e 'clear Lock' -e 'keycode 0x42 = Escape'

# hide mouse on writting
if $(hash unclutter); then
    unclutter -idle 1 &
fi

# music daemon
if $(hash mpd); then
    mpd &
fi

# gnome settings daemon (for fonts and gtk styling)
# gnome-settings-daemon &

# set background
# gsettings set org.gnome.desktop.background picture-uri file:///home/user/Pictures/wallpaper.png
$bspdir/iq_utilities/terminal_transparency 6

# feh --bg-tile $bspdir/wallpaper.jpg &
feh --bg-tile ~/.config/tq_wallpaper &

[[ -e $dunst/dunst ]] \
    && $dunst/dunst -config $bspdir/vq_panels/dunstrc &

# launch compton compositor
[[ -e $compton/compton ]] \
  && $compton/compton --config $bspdir/compton.conf &

# launch dzen2 panels
$bspdir/vq_panels/topbar &
    $bspdir/vq_panels/status &

# launch battery checker
# $bspdir/iq_utilities/battery_alert &

sleep 5 && $bspdir/iq_utilities/hide dzen2-bottom-status-bar

wait
