#! /bin/sh

# rules
# bspc rule -a URxvtScratch sticky=on floating=on
# bspc monitor -d I II III IV V VI VII VIII IX X

# bspc rule -a Gimp desktop=^8 follow=on floating=on
# bspc rule -a Chromium desktop=^2
# # bspc rule -a mplayer2 floating=on
# bspc rule -a Kupfer.py focus=on
# bspc rule -a Screenkey manage=off


bspc control --put-status
bspc control --subscribe > "$PANEL_FIFO" &
bspc config rule_command "$HOME/bin/rule_command"
$HOME/.config/bspwm/bspwm_rules
# For adding panelling
panel &
